// Service exports
export * from './auth.service'
export * from './document.service'
export * from './search.service'
export * from './audit.service'
export * from './queue.service'
export * from './enrichment.service'
export * from './access-request.service'
export * from './lifecycle.service'
export * from './storage.service'

// Service instances
export { authService } from './auth.service'
export { documentService } from './document.service'
export { searchService } from './search.service'
export { auditService } from './audit.service'
export { queueService } from './queue.service'
export { enrichmentService } from './enrichment.service'
export { accessRequestService } from './access-request.service'
export { lifecycleService } from './lifecycle.service'
export { storageService } from './storage.service' 